version: '3.8'
services:
  email_front:
    networks:
        - email_front
        - nginx_network

networks:
    email_front:
    nginx_network: # This networks contains nginx-proxy, already exists.
        external: true
        name: backend_nginx_network
